apiVersion: apps/v1
kind: Deployment
metadata:
  name: cognitive-system
  labels:
    app: cognitive-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cognitive-system
  template:
    metadata:
      labels:
        app: cognitive-system
    spec:
      containers:
      - name: cognitive-system
        image: cognitive-system:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        env:
        - name: COGNITIVE_CONFIG
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cognitive-system-service
spec:
  selector:
    app: cognitive-system
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
